pipeline {
    agent { label 'docker-builder' }

    parameters {
        string(name: 'target', defaultValue: '')
        string(name: 'GERRIT_REFSPEC', defaultValue: 'refs/heads/master')
        string(name: 'GERRIT_PROJECT', defaultValue: '')
        string(name: 'branch', defaultValue: 'master')
        string(name: 'qemu_image', defaultValue: '')
        string(name: 'qemu_pad', defaultValue: '')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    userRemoteConfigs: [[
                        url: "http://gerrit.openbmc.org/${params.GERRIT_PROJECT}",
                        name: 'gerrit',
                        refspec: params.GERRIT_REFSPEC
                    ]],
                    branches: [[name: params.branch]],
                    extensions: [
                        [$class: 'BuildChooserSetting',
                         buildChooser: [$class: 'GerritTriggerBuildChooser', separator: '#']],
                        [$class: 'WipeWorkspace'],
                        [$class: 'CleanBeforeCheckout'],
                        [$class: 'RelativeTargetDirectory', relativeTargetDir: 'openbmc'],
                        [$class: 'CloneOption', shallow: false, noTags: false, depth: 1]
                    ]
                ])
            }
        }

        stage('Build') {
            steps {
                sh '''#!/bin/sh -xe
                export LANG=en_US.UTF8
                echo "BUILDING TARGET: ${target}"
                cd "${WORKSPACE}" && rm -rf openbmc-build-scripts
                git clone https://github.com/openbmc/openbmc-build-scripts.git
                cd openbmc-build-scripts
                export obmc_dir="${WORKSPACE}/openbmc/"
                export build_dir="${WORKSPACE}/build"
                export num_cpu=$((`nproc` / 2))
                [ "$num_cpu" -gt 12 ] && num_cpu=12
                export SDKMACHINE=x86_64
                export img_tag=25.04
                ./build-setup.sh
                '''
            }
        }

        stage('QEMU Test') {
            when {
                expression { params.qemu_image != '' }
            }
            steps {
                script {
                    def image = "${WORKSPACE}/openbmc/build/tmp/deploy/images/${params.target}/${params.qemu_image}"
                    if (params.qemu_pad != '') {
                        sh "cp '${image}' '${image}.padded' && truncate -s ${params.qemu_pad} '${image}.padded'"
                        image = "${image}.padded"
                    }
                    build job: './CI-MISC/run-ci-in-qemu',
                        parameters: [string(name: 'image_location', value: image)],
                        wait: true
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'openbmc/build/tmp/deploy/images/**',
                            allowEmptyArchive: true
            cleanWs()
        }
    }
}
