def branch = ''
def config = [:]
def buildTargets = []

pipeline {
    agent { label 'docker-builder' }

    parameters {
        string(name: 'GERRIT_REFSPEC', defaultValue: 'refs/heads/master')
        string(name: 'GERRIT_PROJECT', defaultValue: '')
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '3'))
        timestamps()
        throttleJobProperty(
            categories: ['ci-openbmc'],
            maxConcurrentTotal: 3,
            maxConcurrentPerNode: 1,
            throttleEnabled: true,
            throttleOption: 'project'
        )
    }

    stages {
        stage('Init') {
            steps {
                script {
                    config = readJSON file: 'jenkins/machines.json'
                    branch = env.GERRIT_BRANCH ?: 'master'
                    def machines = config[branch]
                    if (machines == null) {
                        error "Unknown branch: ${branch}"
                    }
                    buildTargets = machines.findAll { k, v -> v.build }.keySet() as List
                    buildTargets.add('repotest')
                    echo "Building targets for ${branch}: ${buildTargets}"
                }
            }
        }

        stage('Set Build Name') {
            steps {
                script {
                    currentBuild.displayName = "#${BUILD_NUMBER}-${env.GERRIT_PATCHSET_UPLOADER_NAME}-${env.GERRIT_PROJECT}"
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    userRemoteConfigs: [[
                        url: "http://gerrit.openbmc.org/${params.GERRIT_PROJECT}",
                        name: 'gerrit',
                        refspec: params.GERRIT_REFSPEC
                    ]],
                    branches: [[name: branch]],
                    extensions: [
                        [$class: 'BuildChooserSetting',
                         buildChooser: [$class: 'GerritTriggerBuildChooser', separator: '#']],
                        [$class: 'WipeWorkspace'],
                        [$class: 'CleanBeforeCheckout'],
                        [$class: 'RelativeTargetDirectory', relativeTargetDir: 'openbmc'],
                        [$class: 'CloneOption', shallow: false, noTags: false, depth: 1]
                    ]
                ])
            }
        }

        stage('Build Matrix') {
            matrix {
                axes {
                    axis {
                        name 'target'
                        values buildTargets
                    }
                }
                stages {
                    stage('Build') {
                        steps {
                            sh '''#!/bin/sh -xe
                            export LANG=en_US.UTF8
                            echo "BUILDING TARGET: ${target}"
                            cd "${WORKSPACE}" && rm -rf openbmc-build-scripts
                            git clone https://github.com/openbmc/openbmc-build-scripts.git
                            cd openbmc-build-scripts
                            export obmc_dir="${WORKSPACE}/openbmc/"
                            export build_dir="${WORKSPACE}/build"
                            export num_cpu=$((`nproc` / 2))
                            [ "$num_cpu" -gt 12 ] && num_cpu=12
                            export SDKMACHINE=x86_64
                            export img_tag=25.04
                            ./build-setup.sh
                            '''
                        }
                    }
                    stage('QEMU Test') {
                        when {
                            expression { config[branch][target]?.qemu != null }
                        }
                        steps {
                            script {
                                def qemu = config[branch][target].qemu
                                def image = "${WORKSPACE}/openbmc/build/tmp/deploy/images/${target}/${qemu.image}"
                                if (qemu.pad) {
                                    sh "cp '${image}' '${image}.padded' && truncate -s ${qemu.pad} '${image}.padded'"
                                    image = "${image}.padded"
                                }
                                build job: './CI-MISC/run-ci-in-qemu',
                                    parameters: [string(name: 'image_location', value: image)],
                                    wait: true
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'openbmc/build/tmp/deploy/images/**',
                            allowEmptyArchive: true
            cleanWs()
        }
    }
}