#!/bin/bash -xe
#
# Purpose:
#  This script is responsible for testing the openbmc-build-scripts repository
#
# Required Inputs:
#  WORKSPACE:      Directory which contains the extracted openbmc-build-scripts
#                  directory

export LANG=en_US.UTF8

cd "${WORKSPACE}/openbmc-build-scripts"

# Now run some of our most used CI scripts
./scripts/build-unit-test-docker
./scripts/clean-unit-test-docker
./scripts/build-qemu-robot-docker.sh

# Run a simple CI against 'sdbusplus' to ensure the run-unit-test script works.
cd "${WORKSPACE}"
git clone https://github.com/openbmc/openpower-hw-diags
UNIT_TEST_PKG=openpower-hw-diags "${WORKSPACE}/openbmc-build-scripts/run-unit-test-docker.sh"
