apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xcat
  namespace: openbmc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xcat
  template:
    metadata:
      labels:
        app: xcat
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      securityContext:
        runAsUser: 0
      containers:
      - image: master.cfc:8500/openbmc/xcat-amd64
        name: xcat
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 4000
          name: rest-api
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
      imagePullSecrets:
      - name: regkey
